print("*".center(80, '*'))
print("Welcome to the Mini Mental Status examination - Written on Python 3.7.2, Version 1.0, Software copyright - Dr Hrishikesh Sarkar ")
print("*".center(80, '*'))
print()
print("Enter 1 for each correct task unless specified")
print()

print("Orientation:")
print("*".ljust(26, '*'))
print()
print("What is the year ?")
year2 = int(input())
print("What is the season?")
season = int(input())
print("What is the day ?")
day = int(input())
print("What is the date ?")
year1 = int(input())
print("What is the month ?")

month = int(input())
print("Where are we? ")
we = int(input())
print("Which state?")
state = int(input())
print("Which district?")
district = int(input())
print("Which town?")
town = int(input())
print("Name of the hospital?")
hospital = int(input())
print("Which floor?")
floor = int(input())
print()
      
print("Registration")
print("*".ljust(26, '*'))
print()
print("Name three unrelated objects. Allow one second to say each. Then ask the patient to repeat all three after you have said them. Give one point for " + \
      "each correct answer. Repeat them until he or she learns all three. Count trials and record. Enter no of trials (Out of 3)")
register = int(input())
print()
print("Attention and Calculation")
print("*".ljust(26, '*'))
print()
print("Ask patient to count backwards from 100 by sevens. Give one point for each correct answer. Stop after five answers. Alternatively, spell world backwards.(Out of 5)")
attention = int(input())
print()
print("Recall")
print("*".ljust(26, '*'))
print()
print("Ask patient to recall the three objects previously stated. Give one point for each correct answer.(out of 3)")
recall = int(input())
print()
print("Language")
print("*".ljust(26, '*'))
print()
print("Show patient a wrist watch; ask patient what it is. Repeat for a pencil. (2 points)")
language = int(input())
print("Ask patient to repeat the following: \"No ifs, ands, or buts.\") (1 point)")
ifnbut = int(input())
print("Ask patient to follow a three-stage command: \"Take a paper in your right hand, fold it in half, and put it on the floor.\" (3 points)")
three = int(input())
print("Ask patient to read and obey the following sentence which you have written on a piece of paper: \"Close your eyes.\"(1 point)")
read = int(input())
print("Ask patient to write a sentence.(1 point)")
write = int(input())
print("Ask patient to copy a design. (1 point)")
copy = int(input())

print()

MMSEscore = copy + write + read + three + ifnbut + language + recall + attention + register + floor + hospital + town + district + state + we + month + year1 + day + season + year2
print("*".center(80, '*'))
print("Thank you for filling details. The MMSE score is " + str(MMSEscore) + ".")

if MMSEscore <= 17:
    print(" This patient has severe cognitive dysfunction.")
if MMSEscore >=18 and MMSEscore <= 23:
    print("This patient has mild to moderate cognitive dysfunction.")
if MMSEscore >= 24:
    print("This patient is unlikely to have a cognitive dysfunction.")
print("*".center(80, '*'))
